meta_product_name: "re:co"
meta_title: "Recommendations from people you trust!"
meta_description: "re:co is an app designed for creating and sharing recommendation lists with friends!"
meta_image: "cover.jpg" # should exist in `app/assets/images/`
